name: Adicionar CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  workflows: write
  packages: write
  id-token: write

defaults:
  run:
    shell: bash

env:
  GPG_TTY: /dev/tty

jobs:
  build-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt update
          sudo apt install -y apt-utils apt-ftparchive gnupg gzip

      - name: Importar chave GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          gpg --list-keys

      - name: Permitir Git no workspace
        run: git config --global --add safe.directory /github/workspace

      - name: Tornar script executável
        run: chmod +x build-repo.sh

      - name: Executar script
        run: ./build-repo.sh

      - name: Push automático
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "CI/CD"
          git config user.email "actions@github.com"
          git remote set-url origin https://$PAT@github.com/leziriaos-tejo/leziriaos.git
          git push
